### ISSUE TITLE
"Your first plugin" link error

### ISSUE THREAD

**Issue by fengwz17** [ISCAS-PMC/ePMC#3]
On the right of the page "Add a Plugin in EPMC" ([https://github.com/ISCAS-PMC/ePMC/wiki/Add-a-Plugin-in-EPMC](https://github.com/ISCAS-PMC/ePMC/wiki/Add-a-Plugin-in-EPMC)), there is a part " Getting Involved ".

The second item of this part "Your First Plugin" has a wrong link: [https://github.com/ISCAS-PMC/ePMC/Your-First-Plugin](https://github.com/ISCAS-PMC/ePMC/Your-First-Plugin). There will be  "Page not found" after clicking this item.

Maybe this wrong link should be corrected as [https://github.com/ISCAS-PMC/ePMC/wiki/Your-First-Plugin](https://github.com/ISCAS-PMC/ePMC/wiki/Your-First-Plugin).

**Comment by andreat** [comment]
The link is now pointing to the right page.
